dependencies:
- name: spark-cluster
  version: "2.0.0"
  repository: "https://jahstreet.github.io/helm-charts"
  # repository: "file://spark-cluster"

- name: daskhub 
  # repository: "file://daskhub"
  repository: "https://helm.dask.org/"
  version: "4.5.1"
