##  Note that helm by default only runs the daskhub specification of jupyterhub
##  Overrides here are to ensure that the livy version still runs properly
##  And adds profile list to switch between the underlying images

daskhub:
  jupyterhub:
    singleuser:
      extraEnv:
        # The default worker image matches the singleuser image.
        DASK_GATEWAY__CLUSTER__OPTIONS__IMAGE: '{JUPYTER_IMAGE_SPEC}'
        DASK_DISTRIBUTED__DASHBOARD_LINK: '/user/{JUPYTERHUB_USER}/proxy/{port}/status'
        DASK_LABEXTENSION__FACTORY__MODULE: 'dask_gateway'
        DASK_LABEXTENSION__FACTORY__CLASS: 'GatewayCluster'
      storage:
        capacity: 2Gi
        homeMountPath: /home/jovyan/notebooks

      profileList:
      # https://jupyter-docker-stacks.readthedocs.io/en/latest/using/specifics.html#apache-spark
      - display_name: "Big Data Image"
        description: "Sparkmagic + Daskgateway Image"
        default: True
        kubespawner_override:
          environment:
            # For Sparkmagic Kernel
            LIVY_ENDPOINT: "http://livy-server:80"
          cmd:
          - "/opt/singleuser-entrypoint.sh"
          - "--NotebookApp.notebook_dir=/home/jovyan/notebooks"
          image: "kprifogle/base-notebook:0.0.7"
      defaultUrl: "/lab"
